pizzeria/pizzas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),

	url(r'^topics/$',views.topics,name='topics'),
]

pizzeria/pizzeria/urls.py
from django.conf.urls import include,url
from django.contrib import admin


urlpatterns = [
url(r'^admin/', include(admin.site.urls)),
url(r'', include('pizzas.urls', namespace='pizzas')),
]

pizzeria/pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
	name = models.TextField()

	def __str__(self):
		return self.name

class Topping(models.Model):
	pizza = models.ForeignKey(Pizza)
	name = models.TextField()

	def __str__(self):
		return self.name

pizzeria/pizzas/views.py
from django.shortcuts import render

from .models import Topic

# Create your views here.

def index(request):
	return render(request,'pizzas/index.html')


def topics(request):
	topics = Topic.objects.order_by('date_added')
	context = {'topics':topics}
	return render(request,'pizzas/topics.html',context)

pizzeria/pizzas/templates/pizzas/base.html
<p>

  <a href="{% url 'pizzas:index' %}">Pizzas</a>

 </p>

 {% block content %}{% endblock content %}

pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}


  <p>Pizzas helps you to disie which pizza you want.</p>

{% endblock content %}

pizzeria/pizzas/templates/pizzas/topics.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Topics</p>
    <ul>
      {% for topic in topics %}
        <li>{{topic}}</li>
        {% empty %}
        <li>No topics have been added yet.</li>
      {% endfor %}

    </ul>

  {% endblock content %}